---
# Grafana Alloy role - Handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart alloy
  ansible.builtin.shell:
    cmd: |
      systemctl stop alloy || true
      sleep 2
      systemctl start alloy
  changed_when: true
